### PR TITLE
Consider missing indices in PropertyGenerator

### LINKED ISSUE #76: PropertyGenerator::fromReflection throws E_NOTICE for non-default typed properties
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 4.2.0

Apparently, `\ReflectionClass::getDefaultProperties` doesn't return typed properties without a default value, thus an `E_NOTICE` is emitted when assigning [`$defaultValue`](https://github.com/laminas/laminas-code/blob/4.3.x/src/Generator/PropertyGenerator.php#L38) because it's trying to access an undefined index.

### PR DESCRIPTION
**Pull request by rieschl**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Fix missing array index `E_NOTICE` error in `PropertyGenerator`.

fixes #76

Edit: The test explicitly checks, that typed properties will be ignored when generating the code. Maybe that feature should be implemented in a future release, and that will cause this test to fail.

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
Thanks @rieschl!

File: test/Generator/TestAsset/ClassWithTypedProperty.php [hunk 1]
```diff
@@ -0,0 +1,10 @@
+<?php
+
+declare(strict_types=1);
+
+namespace LaminasTest\Code\Generator\TestAsset;
+
+final class ClassWithTypedProperty
+{
+    public string $typedProperty;
```
Comment (Ocramius) [inline test/Generator/TestAsset/ClassWithTypedProperty.php]: While annoying, it is true that this needs a constructor declared: could you please add one?

**Review by Ocramius — CHANGES_REQUESTED** [review]

File: test/Generator/TestAsset/ClassWithTypedProperty.php (hunk 1 above)
Comment (rieschl) [reply test/Generator/TestAsset/ClassWithTypedProperty.php]: thanks! sure, I just pushed a fix.

**Comment by rieschl** [comment]
This bug is also in the 3.x branch (checked with 3.4.1). Do I have to submit a patch for this version, too?

**Comment by Ocramius** [comment]
> This bug is also in the 3.x branch (checked with 3.4.1). Do I have to submit a patch for this version, too?

IMO no need, unless it it a security issue (not the case - codegen is not supposed to be built upon user input)

**Comment by Ocramius** [comment]
Thanks @rieschl!
